---
title: "Bio-Logging Data Standards Initiatives"
format: 
  html:
    page-layout: full
editor: source
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(DT)

knitr::opts_chunk$set(echo = FALSE)

# change to TRUE below to read in from original google doc
# (like the first time)
# instead of csv file
read_original_doc <- FALSE

# filename for csv file with table data
table_file <- "../data/data-standards-table.csv"
```

```{r}
#| warning: false
#| message: false

if (read_original_doc){
  raw_doc <- readLines("../data/IBioLS Standards WG_ 2023 Updates .txt")
  table_data <- tibble(
    Project = raw_doc[grepl("Project:", raw_doc)] |>
      str_remove_all("Project: "),
    Organization = raw_doc[grepl("Organization/s:", raw_doc)] |>
      str_remove_all("Organization/s: "),
    `Contact Name` = raw_doc[grepl(" name:", raw_doc)] |>
      str_remove_all("Your name: ") |>
      str_remove_all("Contact name: "),
    `Contact Email` = raw_doc[grepl(" email:", raw_doc)]|>
      str_remove_all("Contact email: ") |>
      str_remove_all("Your email: "),
    Description = raw_doc[grepl("Description:", raw_doc)] |>
      str_remove_all("Description: "))
  
  table_data <- table_data |>
    mutate(
      # remove the line below to put contact email info back into the table
      # suppressed for now until we can check with folks re: sharing this info
      `Contact Email` = "",
      `Tags` = "")
  
  write_csv(table_data, "../data/data-standards-table.csv")
}else{
  table_data <- read_csv(table_file,
                         show_col_types = FALSE)
}

# make websites into links not just text
table_data <- table_data |>
  mutate(
    Website = if_else(str_starts(Website, pattern = "http"),
                      Website,
                      paste0("https://", Website)),
    Website = if_else(is.na(Website), Website,
                           paste0('<a href=\"', Website, '">', Website, "</a>")))
```


```{r}
DT::datatable(table_data,
              escape = FALSE,
              options = list(
                pageLength = 20),
              caption = htmltools::tags$caption(
                style = 'caption-side: top; text-align: left;',
                'IN PROGRESS: Community initiatives for harmonizing animal tracking and other bio-logging data and developing prototypes for global standards. Contact ibls.datastandards@gmail.com for more information.'),
              rownames = FALSE)
```


